version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fraud_detection
    ports:
      - "5432:5432"
    networks:
      - fraud_detection
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  training:
    build:
      context: .
      dockerfile: fraud_detection_training/Dockerfile
    environment:
      - FRAUD_DETECTION_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fraud_detection
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fraud_detection
    volumes:
      - ./config:/app/config
      - ./fraud_detection_training/data:/app/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fraud_detection

  api:
    build:
      context: .
      dockerfile: fraud_detection_api/Dockerfile
    environment:
      - FRAUD_DETECTION_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fraud_detection
    ports:
      - "8000:8000"
    depends_on:
      - training
      - db
    volumes:
      - ./config:/app/config
    networks:
      - fraud_detection

networks:
  fraud_detection:
    driver: bridge